spring:
  application:
    name: dh-community
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ma321388
    url: jdbc:mysql:///dh_community?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
  redis:
    # 地址
    host: 127.0.0.1
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: 123456
    # 连接超时时间
    timeout: 10s
    jedis:
      pool:
        max-active: 8
        max-wait: 2000
        max-idle: 8
        min-idle: 0
        time-between-eviction-runs: 1000

# 邮件配置
  mail:
    host: smtp.qq.com
    protocol: smtp
    default-encoding: utf-8
    username: 714954230@qq.com
    password: gyartbrrfxsxbdjc
    properties:
      mail:
        stml:
          ssl:
            enable: true
        debug: true

logging:
  level:
    org.francis.community: debug

# swagger 配置
swagger:
  title: DH人人社区
  description: DH人人社区
  version: 1.0
  enabled: true

# github第三方登录配置
github:
  client:
    id: 562f3f4c493527c1d44d
    secret: f221a3ce2ade6161d3807fe74bbc9ccc7bf9f4f3
  redirect:
    uri: http://localhost:8080/callback/github